"""
server.py — IoT Telemetry Server

Starts two services on the same asyncio event loop:

  1. TCP listener (port 9000)  — accepts Protobuf-encoded sensor readings.
  2. HTTP/WebSocket server (port 8080) — REST API + live WebSocket feed.

Usage:
    python server.py [--tcp-port 9000] [--http-port 8080] [--db sensors.db]

All network code uses asyncio — no threads, no multiprocessing.
"""

import asyncio
import argparse
import json
import logging
import secrets
import struct
import sys
import time

from aiohttp import web
import aiosqlite

# Local modules
sys.path.insert(0, "proto")          # so we can import telemetry_pb2
import telemetry_pb2                 # noqa: E402  (generated by protoc)
from storage import Storage          # noqa: E402
from broadcaster import Broadcaster  # noqa: E402
from negotiation import negotiate, serialise, error_response  # noqa: E402

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s %(name)s  %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger("server")

# ── Shared application state ─────────────────────────────────────
storage = Storage()
broadcaster = Broadcaster()

# ═══════════════════════════════════════════════════════════════════
# TCP — Sensor ingestion
# ═══════════════════════════════════════════════════════════════════

async def handle_sensor_connection(
    reader: asyncio.StreamReader, writer: asyncio.StreamWriter
) -> None:
    """
    Coroutine spawned by asyncio.start_server() for each sensor TCP connection.

    Wire format: 4-byte big-endian length prefix followed by a serialised
    telemetry_pb2.Reading message.  The sensor sends one frame per reading.

    Failure modes handled:
      - ConnectionResetError / IncompleteReadError  → clean disconnect
      - DecodeError  → skip frame, log warning; close after 5 consecutive errors
    """
    addr = writer.get_extra_info("peername")
    log.info("Sensor connected from %s", addr)
    consecutive_errors = 0

    try:
        while True:
            # Read 4-byte length prefix
            raw_len = await asyncio.wait_for(reader.readexactly(4), timeout=60)
            (msg_len,) = struct.unpack(">I", raw_len)

            if msg_len == 0 or msg_len > 1_000_000:
                log.warning("Implausible frame length %d from %s — closing", msg_len, addr)
                break

            raw_msg = await asyncio.wait_for(reader.readexactly(msg_len), timeout=30)

            # Try SensorInfo first (sent once on connect for auto-registration)
            info = telemetry_pb2.SensorInfo()
            try:
                info.ParseFromString(raw_msg)
                if info.id:
                    if not await storage.sensor_exists(info.id):
                        await storage.register_sensor(
                            info.id, info.location,
                            info.sensor_type, info.interval_s or 10
                        )
                        log.info("Auto-registered sensor '%s' from %s", info.id, addr)
                    consecutive_errors = 0
                    continue
            except Exception:
                pass  # not a SensorInfo — fall through to Reading

            # Deserialise as a Reading
            reading = telemetry_pb2.Reading()
            try:
                reading.ParseFromString(raw_msg)
                consecutive_errors = 0
            except Exception as exc:
                consecutive_errors += 1
                log.warning("DecodeError from %s (streak=%d): %s", addr, consecutive_errors, exc)
                if consecutive_errors >= 5:
                    log.error("Too many decode errors from %s — closing connection", addr)
                    break
                continue

            log.debug("Reading  sensor=%s  ts=%d  value=%.2f  unit=%s",
                      reading.sensor_id, reading.timestamp, reading.value, reading.unit)

            # Persist to SQLite
            try:
                await storage.store_reading(
                    reading.sensor_id, reading.timestamp,
                    reading.value, reading.unit
                )
            except Exception as exc:
                log.error("Storage write failed for %s: %s", reading.sensor_id, exc)
                # Keep the TCP connection alive; just drop this one reading.

            # Broadcast to WebSocket clients (never blocks)
            broadcaster.publish({
                "sensor_id": reading.sensor_id,
                "timestamp": reading.timestamp,
                "value":     reading.value,
                "unit":      reading.unit,
            })

    except (asyncio.IncompleteReadError, ConnectionResetError):
        log.info("Sensor %s disconnected", addr)
    except asyncio.TimeoutError:
        log.warning("Sensor %s timed out", addr)
    except Exception as exc:
        log.exception("Unexpected error from %s: %s", addr, exc)
    finally:
        writer.close()
        try:
            await writer.wait_closed()
        except Exception:
            pass


# ═══════════════════════════════════════════════════════════════════
# Cookie helpers
# ═══════════════════════════════════════════════════════════════════

SESSION_COOKIE = "session_id"


def _ensure_session(request: web.Request, response: web.Response) -> None:
    """
    Set a session cookie on the response if the request did not include one.
    The cookie value is a random hex token; no server-side state is stored.
    """
    if SESSION_COOKIE not in request.cookies:
        token = secrets.token_hex(16)
        response.set_cookie(
            SESSION_COOKIE, token,
            httponly=True, samesite="Lax", max_age=86400 * 30
        )


# ═══════════════════════════════════════════════════════════════════
# REST handlers
# ═══════════════════════════════════════════════════════════════════

async def get_sensors(request: web.Request) -> web.Response:
    """GET /sensors — list all registered sensors."""
    media = negotiate(request)
    try:
        sensors = await storage.get_sensors()
    except Exception as exc:
        log.error("Storage error in get_sensors: %s", exc)
        return error_response(503, "storage unavailable", str(exc))

    resp = serialise(sensors, media, root="sensors")
    _ensure_session(request, resp)
    return resp


async def get_sensor(request: web.Request) -> web.Response:
    """GET /sensors/{id} — get one sensor by ID."""
    sensor_id = request.match_info["id"]
    media = negotiate(request)
    try:
        sensor = await storage.get_sensor(sensor_id)
    except Exception as exc:
        log.error("Storage error in get_sensor: %s", exc)
        return error_response(503, "storage unavailable", str(exc))

    if sensor is None:
        return error_response(404, "sensor not found", f"id={sensor_id}")

    resp = serialise(sensor, media, root="sensor")
    _ensure_session(request, resp)
    return resp


async def post_sensor(request: web.Request) -> web.Response:
    """POST /sensors — register a new sensor."""
    try:
        body = await request.json()
    except Exception:
        return error_response(400, "invalid JSON body")

    sensor_id    = body.get("id", "").strip()
    location     = body.get("location", "").strip()
    sensor_type  = body.get("sensor_type", "").strip()
    interval_s   = int(body.get("interval_s", 10))

    if not sensor_id or not location or not sensor_type:
        return error_response(400, "missing required fields", "id, location, sensor_type")

    try:
        if await storage.sensor_exists(sensor_id):
            return error_response(409, "sensor already registered", f"id={sensor_id}")
        sensor = await storage.register_sensor(sensor_id, location, sensor_type, interval_s)
    except Exception as exc:
        log.error("Storage error in post_sensor: %s", exc)
        return error_response(503, "storage unavailable", str(exc))

    media = negotiate(request)
    resp = serialise(sensor, media, root="sensor")
    resp.set_status(201)
    _ensure_session(request, resp)
    return resp


async def delete_sensor(request: web.Request) -> web.Response:
    """DELETE /sensors/{id} — remove a sensor and its readings."""
    sensor_id = request.match_info["id"]
    try:
        deleted = await storage.delete_sensor(sensor_id)
    except Exception as exc:
        log.error("Storage error in delete_sensor: %s", exc)
        return error_response(503, "storage unavailable", str(exc))

    if not deleted:
        return error_response(404, "sensor not found", f"id={sensor_id}")

    resp = web.Response(status=204)
    _ensure_session(request, resp)
    return resp


async def get_readings(request: web.Request) -> web.Response:
    """GET /sensors/{id}/readings?from=<ms>&to=<ms>"""
    sensor_id = request.match_info["id"]
    media = negotiate(request)

    # Parse optional time-range params
    from_ts = to_ts = None
    try:
        if "from" in request.rel_url.query:
            from_ts = int(request.rel_url.query["from"])
        if "to" in request.rel_url.query:
            to_ts = int(request.rel_url.query["to"])
    except ValueError:
        return error_response(400, "invalid query params", "'from' and 'to' must be Unix ms integers")

    try:
        if not await storage.sensor_exists(sensor_id):
            return error_response(404, "sensor not found", f"id={sensor_id}")
        readings = await storage.get_readings(sensor_id, from_ts, to_ts)
    except Exception as exc:
        log.error("Storage error in get_readings: %s", exc)
        return error_response(503, "storage unavailable", str(exc))

    resp = serialise(readings, media, root="readings")
    _ensure_session(request, resp)
    return resp


# ═══════════════════════════════════════════════════════════════════
# WebSocket handler
# ═══════════════════════════════════════════════════════════════════

async def websocket_handler(request: web.Request) -> web.WebSocketResponse:
    """
    GET /live — WebSocket live feed.

    The server pushes every incoming sensor reading as a JSON object.
    Clients may optionally send a JSON filter:
        {"sensor_id": "gh_a_temp_01"}
    to receive readings only from that sensor.
    """
    ws = web.WebSocketResponse(heartbeat=30)
    await ws.prepare(request)
    log.info("WebSocket client connected from %s", request.remote)

    q = broadcaster.register()
    sensor_filter: str | None = None

    try:
        # Run reader and writer tasks concurrently.
        async def _writer():
            while True:
                reading = await q.get()
                if sensor_filter and reading["sensor_id"] != sensor_filter:
                    continue
                try:
                    await ws.send_json(reading)
                except Exception:
                    break

        async def _reader():
            nonlocal sensor_filter
            async for msg in ws:
                if msg.type == web.WSMsgType.TEXT:
                    try:
                        data = json.loads(msg.data)
                        if "sensor_id" in data:
                            sensor_filter = data["sensor_id"]
                            log.debug("WS client filtered to sensor_id=%s", sensor_filter)
                    except json.JSONDecodeError:
                        pass
                elif msg.type in (web.WSMsgType.ERROR, web.WSMsgType.CLOSE):
                    break

        writer_task = asyncio.create_task(_writer())
        await _reader()
        writer_task.cancel()
        try:
            await writer_task
        except asyncio.CancelledError:
            pass

    finally:
        broadcaster.unregister(q)
        log.info("WebSocket client disconnected from %s", request.remote)

    return ws


# ═══════════════════════════════════════════════════════════════════
# Dashboard (optional HTML page)
# ═══════════════════════════════════════════════════════════════════

DASHBOARD_HTML = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Telemetry Dashboard</title>
<style>
  body { font-family: monospace; background: #0d0f14; color: #dce3f0; margin: 40px; }
  h1 { color: #4af0a8; }
  #feed { border: 1px solid #272d3b; padding: 16px; height: 400px; overflow-y: auto; background: #0b0d12; }
  .reading { margin: 4px 0; }
  .ts { color: #5b8fff; }
  .val { color: #4af0a8; font-weight: bold; }
</style>
</head>
<body>
<h1>Live Sensor Feed</h1>
<p>Connecting to <code>ws://localhost:8080/live</code>…</p>
<div id="feed"></div>
<script>
  const feed = document.getElementById('feed');
  const ws = new WebSocket('ws://' + location.host + '/live');
  ws.onopen  = () => feed.insertAdjacentHTML('afterbegin', '<p style="color:#4af0a8">Connected.</p>');
  ws.onclose = () => feed.insertAdjacentHTML('afterbegin', '<p style="color:#f06450">Disconnected.</p>');
  ws.onmessage = e => {
    const r = JSON.parse(e.data);
    const d = new Date(r.timestamp);
    feed.insertAdjacentHTML('afterbegin',
      '<div class="reading"><span class="ts">' + d.toLocaleTimeString() + '</span>  ' +
      r.sensor_id + '  <span class="val">' + r.value.toFixed(2) + ' ' + r.unit + '</span></div>');
  };
</script>
</body>
</html>
"""


async def dashboard(request: web.Request) -> web.Response:
    return web.Response(text=DASHBOARD_HTML, content_type="text/html")


# ═══════════════════════════════════════════════════════════════════
# Application factory & entry point
# ═══════════════════════════════════════════════════════════════════

def make_app() -> web.Application:
    app = web.Application()
    app.router.add_get("/",                          dashboard)
    app.router.add_get("/sensors",                   get_sensors)
    app.router.add_get("/sensors/{id}",              get_sensor)
    app.router.add_post("/sensors",                  post_sensor)
    app.router.add_delete("/sensors/{id}",           delete_sensor)
    app.router.add_get("/sensors/{id}/readings",     get_readings)
    app.router.add_get("/live",                      websocket_handler)
    return app


async def main(tcp_port: int, http_port: int, db_path: str) -> None:
    # Open storage
    await storage.connect()
    log.info("Database ready at %s", db_path)

    # Start TCP sensor listener
    tcp_server = await asyncio.start_server(
        handle_sensor_connection, "0.0.0.0", tcp_port
    )
    log.info("TCP sensor listener on port %d", tcp_port)

    # Start HTTP/WebSocket server
    app = make_app()
    runner = web.AppRunner(app)
    await runner.setup()
    site = web.TCPSite(runner, "0.0.0.0", http_port)
    await site.start()
    log.info("HTTP/WebSocket server on http://0.0.0.0:%d", http_port)
    log.info("Dashboard: http://localhost:%d/", http_port)

    try:
        async with tcp_server:
            await asyncio.Event().wait()          # run forever
    except asyncio.CancelledError:
        pass
    finally:
        await runner.cleanup()
        await storage.close()
        log.info("Server shut down")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="IoT Telemetry Server")
    parser.add_argument("--tcp-port",  type=int, default=9000)
    parser.add_argument("--http-port", type=int, default=8080)
    parser.add_argument("--db",        type=str, default="sensors.db")
    args = parser.parse_args()

    try:
        asyncio.run(main(args.tcp_port, args.http_port, args.db))
    except KeyboardInterrupt:
        log.info("Interrupted — bye")
